{{ $outer := .}}
{{- range (until (int .Values.replicaCount)) -}}
apiVersion: horcrux.dev/v1alpha1
kind: XHorcrux
metadata:
  name: {{ include "deploy-chart.fullname" $outer }}-{{.}}
spec: {}
---
{{ end }}